[2022-07-28 15:09:43,949] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: SAVE_historic_data.create_historic_table scheduled__2022-07-28T14:30:00+00:00 [queued]>
[2022-07-28 15:09:44,008] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: SAVE_historic_data.create_historic_table scheduled__2022-07-28T14:30:00+00:00 [queued]>
[2022-07-28 15:09:44,009] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 15:09:44,009] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-28 15:09:44,012] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 15:09:44,103] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_historic_table> on 2022-07-28 14:30:00+00:00
[2022-07-28 15:09:44,110] {standard_task_runner.py:52} INFO - Started process 821 to run task
[2022-07-28 15:09:44,121] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'SAVE_historic_data', 'create_historic_table', 'scheduled__2022-07-28T14:30:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmpvrganyan', '--error-file', '/tmp/tmpatc6tuka']
[2022-07-28 15:09:44,147] {standard_task_runner.py:80} INFO - Job 110: Subtask create_historic_table
[2022-07-28 15:09:44,493] {task_command.py:371} INFO - Running <TaskInstance: SAVE_historic_data.create_historic_table scheduled__2022-07-28T14:30:00+00:00 [running]> on host a2299eb83309
[2022-07-28 15:09:45,654] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=SAVE_historic_data
AIRFLOW_CTX_TASK_ID=create_historic_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T14:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-28T14:30:00+00:00
[2022-07-28 15:09:45,718] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-28 15:09:45,760] {dbapi.py:231} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS historic__SAVE_ (
            datetime BIGINT,
            high DOUBLE PRECISION,
            low DOUBLE PRECISION,
            open DOUBLE PRECISION,
            close DOUBLE PRECISION,
            volume INTEGER,
            symbol VARCHAR(32) NOT NULL,
            PRIMARY KEY (symbol, datetime)
        )
    , parameters: None
[2022-07-28 15:09:45,818] {python.py:173} INFO - Done. Returned value was: None
[2022-07-28 15:09:45,873] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=SAVE_historic_data, task_id=create_historic_table, execution_date=20220728T143000, start_date=20220728T150943, end_date=20220728T150945
[2022-07-28 15:09:45,961] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-28 15:09:46,385] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
